### ISSUE TITLE
image URLs not working

### ISSUE THREAD

**Issue by drnic** [shieldproject/website#20]
https://shieldproject.io/docs/latest/ops/getting-started/ references images urls that do not exist such as https://shieldproject.io/docs/8.6.2/ops/getting-started/login.png

<img width="802" alt="image" src="https://user-images.githubusercontent.com/108/70322534-11ad5080-1876-11ea-9ac8-e0c0535a20f3.png">

**Comment by blacks1ne** [comment]
Indeed, I have the same experience with v8.6.3.

![Screenshot_20200119-111852__01](https://user-images.githubusercontent.com/3999712/72678344-9f9f6c80-3aad-11ea-84a1-f6145a201b24.jpg)

An attempt to find the images in the project tree (in case they were not migrated properly from an old version) failed.
